FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git curl libpng-dev libonig-dev \
    libxml2-dev zip unzip libpq-dev

RUN docker-php-ext-install pdo pdo_pgsql mbstring exif bcmath

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/backend

RUN chown -R www-data:www-data /var/www/backend